name: CI

on:
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PIPENV_VENV_IN_PROJECT: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'


      - name: Install
        id: install
        run: |
          pip install pipenv
          pipenv install --dev --skip-lock

      - name: Download Model
        id: download
        run: |
          cd model/cpu
          pipenv run gdown https://drive.google.com/uc?id=1T6CfksQYmt-4279Wwac-wZlBRLgvrMNo
          cd ../..

      - name: Lint
        if: success() || steps.install.outcome == 'success'
        run: pipenv run lint
      
      - name: Code Style
        if: success() || steps.install.outcome == 'success'
        run: pipenv run black ebl_ai --check

      - name: Type Check
        if: success() || steps.install.outcome == 'success'
        run: pipenv run pyre check

      - name: Unit Tests
        id: unit_tests
        env:
          CI: true
        run: pipenv run pytest